CREATE TABLE `wp_terms` (  `term_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `name` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '',  `slug` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '',  `term_group` bigint(10) NOT NULL DEFAULT '0',  PRIMARY KEY (`term_id`),  KEY `slug` (`slug`(191)),  KEY `name` (`name`(191))) ENGINE=MyISAM AUTO_INCREMENT=90 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
/*!40000 ALTER TABLE `wp_terms` DISABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
INSERT INTO `wp_terms` VALUES('1', 'Uncategorized', 'uncategorized', '0');
INSERT INTO `wp_terms` VALUES('2', 'Blogroll', 'blogroll', '0');
INSERT INTO `wp_terms` VALUES('6', 'Laboratory', 'laboratory', '0');
INSERT INTO `wp_terms` VALUES('7', 'Medical Device', 'medical-device', '0');
INSERT INTO `wp_terms` VALUES('8', 'Biotechnology', 'biotechnology', '0');
INSERT INTO `wp_terms` VALUES('9', 'Pharmaceutical', 'pharmaceutical', '0');
INSERT INTO `wp_terms` VALUES('10', 'Solujet', 'solujet', '0');
INSERT INTO `wp_terms` VALUES('11', 'Cosmetics', 'cosmetics', '0');
INSERT INTO `wp_terms` VALUES('12', 'Electronics', 'electronics', '0');
INSERT INTO `wp_terms` VALUES('13', 'Environmental', 'environmental', '0');
INSERT INTO `wp_terms` VALUES('14', 'Food/Beverage', 'foodbeverage', '0');
INSERT INTO `wp_terms` VALUES('15', 'Food', 'food', '0');
INSERT INTO `wp_terms` VALUES('17', 'Healthcare/Veterinary', 'healthcareveterinary', '0');
INSERT INTO `wp_terms` VALUES('18', 'Optics', 'optics', '0');
INSERT INTO `wp_terms` VALUES('19', 'Passivation', 'passivation', '0');
INSERT INTO `wp_terms` VALUES('20', 'Pharmaceutical/Biotechnology', 'pharmaceuticalbiotechnology', '0');
INSERT INTO `wp_terms` VALUES('21', 'Precision Manufacturing', 'precision-manufacturing', '0');
INSERT INTO `wp_terms` VALUES('22', 'Electronics/Photovoltaic', 'electronicsphotovoltaic', '0');
INSERT INTO `wp_terms` VALUES('23', 'Restaurant/Food Service', 'restaurantfood-service', '0');
INSERT INTO `wp_terms` VALUES('88', 'Main Menu', 'main-menu', '0');
INSERT INTO `wp_terms` VALUES('89', 'Support', 'support', '0');
INSERT INTO `wp_terms` VALUES('26', 'Electronics &amp; Photovoltaic', 'electronics-photovoltaic', '0');
INSERT INTO `wp_terms` VALUES('27', 'Alcojet', 'alcojet', '0');
INSERT INTO `wp_terms` VALUES('28', 'Food/Beverage Manufacturing', 'foodbeverage-manufacturing', '0');
INSERT INTO `wp_terms` VALUES('29', 'Alconox', 'alconox', '0');
INSERT INTO `wp_terms` VALUES('30', 'Citrajet', 'citrajet', '0');
INSERT INTO `wp_terms` VALUES('31', 'Citranox', 'citranox', '0');
INSERT INTO `wp_terms` VALUES('32', 'Detojet', 'detojet', '0');
INSERT INTO `wp_terms` VALUES('33', 'Alcotabs', 'alcotabs', '0');
INSERT INTO `wp_terms` VALUES('34', 'Detergent 8', 'detergent-8', '0');
INSERT INTO `wp_terms` VALUES('35', 'Liquinox', 'liquinox', '0');
INSERT INTO `wp_terms` VALUES('36', 'Luminox', 'luminox', '0');
INSERT INTO `wp_terms` VALUES('37', 'Tergajet', 'tergajet', '0');
INSERT INTO `wp_terms` VALUES('38', 'Tergazyme', 'tergazyme', '0');
INSERT INTO `wp_terms` VALUES('42', 'First form', 'first-form', '0');
INSERT INTO `wp_terms` VALUES('43', 'Dealer', 'dealer', '0');
INSERT INTO `wp_terms` VALUES('48', 'Contact Form 7', 'contact-form-7', '0');
INSERT INTO `wp_terms` VALUES('49', 'Consultation Form', 'untitled', '0');
INSERT INTO `wp_terms` VALUES('50', 'US Dealers', 'us-dealers', '0');
INSERT INTO `wp_terms` VALUES('51', 'International Dealers', 'international-dealers', '0');
INSERT INTO `wp_terms` VALUES('54', 'Alconox COA', 'alconox-coa', '0');
INSERT INTO `wp_terms` VALUES('57', 'Alconox COA', 'alconox-coa', '0');
INSERT INTO `wp_terms` VALUES('58', 'Alconox COA', 'alconox-coa', '0');
INSERT INTO `wp_terms` VALUES('60', 'Technotes', 'technotes', '0');
INSERT INTO `wp_terms` VALUES('61', 'jewelry', 'jewelry', '0');
INSERT INTO `wp_terms` VALUES('62', 'Keylajet', 'keylajet', '0');
INSERT INTO `wp_terms` VALUES('63', 'Detonox', 'detonox', '0');
INSERT INTO `wp_terms` VALUES('64', 'Liqui-nox', 'liqui-nox', '0');
INSERT INTO `wp_terms` VALUES('65', 'find dealer', 'find-dealer', '0');
INSERT INTO `wp_terms` VALUES('66', 'locate dealer', 'locate-dealer', '0');
INSERT INTO `wp_terms` VALUES('67', 'find my dealer', 'find-my-dealer', '0');
INSERT INTO `wp_terms` VALUES('68', 'search dealer', 'search-dealer', '0');
INSERT INTO `wp_terms` VALUES('69', 'search', 'search', '0');
INSERT INTO `wp_terms` VALUES('70', 'locate', 'locate', '0');
INSERT INTO `wp_terms` VALUES('71', 'local dealers', 'local-dealers', '0');
INSERT INTO `wp_terms` VALUES('72', 'international dealers', 'international-dealers', '0');
INSERT INTO `wp_terms` VALUES('73', 'simple', 'simple', '0');
INSERT INTO `wp_terms` VALUES('74', 'grouped', 'grouped', '0');
INSERT INTO `wp_terms` VALUES('75', 'variable', 'variable', '0');
INSERT INTO `wp_terms` VALUES('76', 'external', 'external', '0');
INSERT INTO `wp_terms` VALUES('77', 'exclude-from-search', 'exclude-from-search', '0');
INSERT INTO `wp_terms` VALUES('78', 'exclude-from-catalog', 'exclude-from-catalog', '0');
INSERT INTO `wp_terms` VALUES('79', 'featured', 'featured', '0');
INSERT INTO `wp_terms` VALUES('80', 'outofstock', 'outofstock', '0');
INSERT INTO `wp_terms` VALUES('81', 'rated-1', 'rated-1', '0');
INSERT INTO `wp_terms` VALUES('82', 'rated-2', 'rated-2', '0');
INSERT INTO `wp_terms` VALUES('83', 'rated-3', 'rated-3', '0');
INSERT INTO `wp_terms` VALUES('84', 'rated-4', 'rated-4', '0');
INSERT INTO `wp_terms` VALUES('85', 'rated-5', 'rated-5', '0');
INSERT INTO `wp_terms` VALUES('86', 'Uncategorized', 'uncategorized', '0');
INSERT INTO `wp_terms` VALUES('87', 'wc-admin-notes', 'wc-admin-notes', '0');
/*!40000 ALTER TABLE `wp_terms` ENABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
